"use client";
import { Canvas, useFrame } from "@react-three/fiber";
import { Float, MeshDistortMaterial } from "@react-three/drei";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowUpRight, Github, ShieldCheck, Wallet } from "lucide-react";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import type { Mesh } from "three";
import { ALPHA_CONTRACT, ALPHA_SUPPLY, BASE_SEPOLIA } from "@/lib/constants";
import { buildIssueUrl, isEvmAddress, normalizeGitHubRepoUrl } from "@/lib/validation";

type EthereumProvider={request(args:{method:string;params?:unknown[]}):Promise<unknown>;on?(event:string,cb:(...args:unknown[])=>void):void;removeListener?(event:string,cb:(...args:unknown[])=>void):void};
type PublicStatus={metrics:{submitted:number;underReview:number;accepted:number};builders:Array<{issue:number;repoUrl:string;wallet:string;status:string}>};
declare global{interface Window{ethereum?:EthereumProvider}}
function Shape(){const ref=useRef<Mesh>(null);useFrame((_,d)=>{if(ref.current){ref.current.rotation.x+=d*.15;ref.current.rotation.y+=d*.2}});return <Float speed={1.4} rotationIntensity={.4} floatIntensity={.7}><mesh ref={ref}><icosahedronGeometry args={[1.45,5]}/><MeshDistortMaterial color="#b8ff38" roughness={.25} distort={.3} speed={1.2}/></mesh></Float>}
function Orb(){const reduced=useReducedMotion();if(reduced)return <div className="orb-fallback"/>;return <div className="orb" aria-hidden="true"><Canvas dpr={[1,1.5]} camera={{position:[0,0,4]}}><ambientLight intensity={1.7}/><directionalLight position={[3,3,4]} intensity={2}/><Shape/></Canvas></div>}
const short=(v:string)=>v?`${v.slice(0,6)}…${v.slice(-4)}`:"";
export default function AlphaBuildersApp(){
 const [account,setAccount]=useState("");const [chain,setChain]=useState("");const [walletError,setWalletError]=useState("");const [repoUrl,setRepoUrl]=useState("");const [wallet,setWallet]=useState("");const [formError,setFormError]=useState("");const [status,setStatus]=useState<PublicStatus>({metrics:{submitted:0,underReview:0,accepted:0},builders:[]});const provider=typeof window!=="undefined"?window.ethereum:undefined;
 const sync=useCallback(async()=>{if(!provider)return;const a=await provider.request({method:"eth_accounts"}) as string[];const c=await provider.request({method:"eth_chainId"}) as string;setAccount(a[0]??"");setChain(c)},[provider]);
 useEffect(()=>{void fetch("/api/status").then(r=>r.ok?r.json():null).then(v=>{if(v)setStatus(v as PublicStatus)}).catch(()=>undefined)},[]);
 useEffect(()=>{if(!provider)return;void sync();const onA=(v:unknown)=>setAccount(Array.isArray(v)?String(v[0]??""):"");const onC=(v:unknown)=>setChain(String(v));const onD=()=>{setAccount("");setChain("")};provider.on?.("accountsChanged",onA);provider.on?.("chainChanged",onC);provider.on?.("disconnect",onD);return()=>{provider.removeListener?.("accountsChanged",onA);provider.removeListener?.("chainChanged",onC);provider.removeListener?.("disconnect",onD)}},[provider,sync]);
 const connect=async()=>{setWalletError("");if(!provider){setWalletError("Nenhuma carteira EVM detectada.");return}try{const a=await provider.request({method:"eth_requestAccounts"}) as string[];setAccount(a[0]??"");const current=await provider.request({method:"eth_chainId"}) as string;if(current!==BASE_SEPOLIA.chainIdHex){try{await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:BASE_SEPOLIA.chainIdHex}]})}catch{await provider.request({method:"wallet_addEthereumChain",params:[{chainId:BASE_SEPOLIA.chainIdHex,chainName:BASE_SEPOLIA.chainName,nativeCurrency:BASE_SEPOLIA.nativeCurrency,rpcUrls:BASE_SEPOLIA.rpcUrls,blockExplorerUrls:BASE_SEPOLIA.blockExplorerUrls}]})}}await sync()}catch(e){const code=typeof e==="object"&&e&&"code" in e?String((e as {code?:unknown}).code):"";setWalletError(code==="4001"?"Conexão cancelada na carteira.":"Não foi possível conectar a carteira.")}};
 const submit=(e:FormEvent)=>{e.preventDefault();setFormError("");if(!normalizeGitHubRepoUrl(repoUrl)){setFormError("Informe uma URL pública válida do GitHub.");return}if(!isEvmAddress(wallet)){setFormError("Informe um endereço EVM público válido.");return}window.open(buildIssueUrl({repoUrl,wallet}),"_blank","noopener,noreferrer")};
 return <main><header className="nav"><a className="brand" href="#top">ALPHA/BUILDERS</a><div className="wallet-wrap"><button className="button" onClick={connect} type="button"><Wallet size={18}/>{account?short(account):"Conectar carteira"}</button>{account&&<span className={`pill ${chain===BASE_SEPOLIA.chainIdHex?"ok":"warn"}`}>{chain===BASE_SEPOLIA.chainIdHex?"Base Sepolia":"Rede incorreta"}</span>}{walletError&&<span className="error">{walletError}</span>}</div></header>
 <section className="hero" id="top"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}}><span className="eyebrow">BASE SEPOLIA · TESTNET</span><h1>Seu projeto precisa de <em>evidência</em>, não de promessa.</h1><p>Um laboratório aberto para revisar README, mostrar entregas públicas e construir histórico verificável sem vender token ou criar expectativa financeira.</p><div className="hero-actions"><a className="button accent" href="#challenge">Começar desafio</a><a className="button ghost" href="https://github.com/Kadys-dv/ALPHA-Lab" target="_blank" rel="noreferrer"><Github size={18}/> Código público</a></div></motion.div><Orb/></section>
 <section className="metrics"><article><span>ON_CHAIN</span><strong>{ALPHA_SUPPLY}</strong><small>ALPHA supply fixo</small></article><article><span>GITHUB</span><strong>{status.metrics.submitted}</strong><small>submissões públicas</small></article><article><span>GITHUB</span><strong>{status.metrics.underReview}</strong><small>em revisão</small></article><article><span>GITHUB</span><strong>{status.metrics.accepted}</strong><small>aceitas</small></article></section>
 <section className="contract"><div><span className="eyebrow">CONTRATO PÚBLICO</span><h2>Sem owner. Sem mint posterior. Sem venda.</h2></div><code className="contract-box">{ALPHA_CONTRACT}</code></section>
 <section className="challenge" id="challenge"><div><span className="eyebrow">DESAFIO 01</span><h2>Faça seu README provar que o projeto existe.</h2><p>Revise contexto, instalação, decisões técnicas, testes e demonstração. Depois envie o repositório público para revisão.</p><ul><li>Problema explicado em linguagem simples</li><li>Instalação reproduzível</li><li>Stack e decisões técnicas</li><li>Testes ou validações documentados</li><li>Demonstração ou screenshots quando fizer sentido</li></ul><div className="notice"><ShieldCheck size={20}/><span>O fluxo não pede assinatura, transferência, approve, swap, bridge ou staking.</span></div></div><form className="submission" onSubmit={submit}><label>Repositório GitHub<input value={repoUrl} onChange={e=>setRepoUrl(e.target.value)} placeholder="https://github.com/usuario/projeto"/></label><label>Endereço público EVM<input value={wallet} onChange={e=>setWallet(e.target.value)} placeholder="0x…" autoComplete="off"/></label>{formError&&<p className="error" role="alert">{formError}</p>}<button className="button accent" type="submit">Enviar para revisão <ArrowUpRight size={18}/></button><small>Nunca envie chave privada, seed phrase ou dados pessoais.</small></form></section>
 <section id="builders"><span className="eyebrow">HISTÓRICO VERIFICÁVEL</span><h2>Builders aceitos</h2>{status.builders.length===0?<p className="muted">Nenhuma contribuição aceita ainda. A lista nasce somente de Issues públicas revisadas.</p>:<div className="builder-grid">{status.builders.map(builder=><article className="builder-card" key={builder.issue}><span className="pill ok">Accepted</span><h3>Issue #{builder.issue}</h3><a href={builder.repoUrl} target="_blank" rel="noreferrer">Abrir projeto</a><code>{builder.wallet}</code></article>)}</div>}</section><footer><strong>ALPHA Builders</strong><p>Experimento educacional em Base Sepolia. ALPHA não está à venda e não representa investimento.</p></footer></main>}
